name: Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: DimensionDev/github-token-action@latest
        with:
          registry: true
      - run: npm ci
      - run: npm run lint
      - run: npm run set-version
      - run: npm publish
